version: "3"

services:
  web:
    build: "./web"

    volumes:
      - "files:/files"
      - "~/:/projects/"

    ports:
      - "5001:5001"

    # stdin_open: true
    # tty: true
volumes:
  files:
